### ISSUE TITLE
Where is new declaration (.d.ts) file? (typescript import error)

### ISSUE THREAD

**Issue by daoauth** [MetaMask/detect-provider#15]
Could not find a declaration file for module '@metamask/detect-provider'. '/Users/xxxx/GitHub/yyyy/celo-web-signer/node_modules/@metamask/detect-provider/index.js' implicitly has an 'any' type. Try `npm install @types/metamask__detect-provider` if it exists or add a new declaration (.d.ts) file containing `declare module '@metamask/detect-provider';`ts(7016)

**Comment by whymarrh** [comment]
Thanks, we'll ship type definitions with the next version!

**Comment by daoauth** [comment]
When it comes out, I will apply it immediately. Thanks

**Comment by rekmarks** [comment]
We shipped types via #18 in `1.2.0`.
