### ISSUE TITLE
Provider not found in metamask app

### ISSUE THREAD

**Issue by sakshamverenkar** [MetaMask/detect-provider#26]
Dear team
I am using @metamask/provider to detect the provider in my webapp. Upon integration, I tested that it works fine on web (chrome extension) and iOS (metamask app). However, on android (metamask app), its not able to detect the provider. I've added alerts on the page as well to debug the same. On web, the alerts work fine. On android metamask app, it shows provider not found, please install metamask. I'm unable to understand why the same is not getting detected in android app. Please help here.

The url for my webapp - https://fervent-pike-7afa22.netlify.app

**Comment by MrPeanutz** [comment]
Same here, it was also not working on TrustWallet a few months ago and they fixed it, but still not working on metamask

**Comment by gtabia** [comment]
@sakshamverenkar you solve it? I just check your app via metamask android and the result is "provider found". Can you share a solution, please?

**Comment by thedarkknight197** [comment]
> Dear team
> I am using @metamask/provider to detect the provider in my webapp. Upon integration, I tested that it works fine on web (chrome extension) and iOS (metamask app). However, on android (metamask app), its not able to detect the provider. I've added alerts on the page as well to debug the same. On web, the alerts work fine. On android metamask app, it shows provider not found, please install metamask. I'm unable to understand why the same is not getting detected in android app. Please help here.
> 
> The url for my webapp - https://fervent-pike-7afa22.netlify.app

To me your web app don't detect metamask on my iphone 12.

I find your issue because on my web app metamusk is not detected on my phone

**Comment by sakshamverenkar** [comment]
> @sakshamverenkar you solve it? I just check your app via metamask android and the result is "provider found". Can you share a solution, please?

Hi @gtabia  it works for first time sometimes but after that it doesn't work and sometimes it doesn't even detect the first time

**Comment by mcmire** [comment]
I'm going to close this issue. I visited https://fervent-pike-7afa22.netlify.app/ in the MetaMask app (I have Android) and an alert pops up with "provider found" each time. The "Connect Wallet" button doesn't work but that seems unrelated. It would help us if you could share your code so we can understand whether you're using the library correctly.
