### ISSUE TITLE
@metamask/detect-provider: Unable to detect window.ethereum on Android browsers and Metamask app

### ISSUE THREAD

**Issue by tomtomcrypto** [MetaMask/detect-provider#37]
The detect provider is unable to find the provider in Chrome, Android browser & Metamask App on version 10 of Android. Same web app works fine on desktop. Code is from the example given on the metamask docs. No CSP are set. Website was built using Webflow plus custom JS script for Web3. I'm at a complete lose as to what is happening, seems to be the same on dapps like pancakeswap except in Metamask App itself, when I choose Metamask it tells me: provider not found :/

**Comment by yennhan** [comment]
Any resolution so far yet? I am facing the same issue for android app too

**Comment by savi96** [comment]
did this issue fix?i am also looking for a solution for this same issue

**Comment by SwapnilKD** [comment]
Any resolution found yet, any fixes available for this? Im also trying to launch metamask mobile app when click on btn on my website in chrome mobile browser. Please help us fix this issue. window.ethererum is enough to be able to handle the metamask related flow, but its null always on mobile browsers chrome, Mozilla etc.

**Comment by mcmire** [comment]
I'm closing this as the issue described is intended. You need to open up your dapp within the browser that's inside of the MetaMask app in order to detect MetaMask using this library. It won't work outside. I've explained why here: https://github.com/MetaMask/detect-provider/issues/38#issuecomment-1215739459
