### ISSUE TITLE
Where can I find typings for this?

### ISSUE THREAD

**Issue by aksdevac** [MetaMask/detect-provider#6]
provide a way to get typings for typescript projects.

**Comment by Lukasz257** [comment]
Yea

**Comment by rekmarks** [comment]
@aksdevac I apologize for the delay on this. Types will be added to this package via #11, which will close this issue. We will publish an update to this package as soon as that's merged.

It uses types from: https://github.com/MetaMask/inpage-provider

**Comment by pointtoken** [comment]
Please merge this PR!  Thanks!

**Comment by rekmarks** [comment]
We shipped types via #18 in `1.2.0`.

**Comment by schoenwaldnils** [comment]
Thanks for providing types.
I just noticed that the return type of the `detectEthereumProvider` is `Promise<unknown>`
Shouldn't it be something like this?: https://github.com/MetaMask/inpage-provider/blob/main/index.d.ts#L29
