### ISSUE TITLE
Readme's description of the behaviour of mobile apps.

### ISSUE THREAD

**Issue by uji** [MetaMask/detect-provider#72]
[README](https://github.com/MetaMask/detect-provider/blob/0db9e6c57464bcaef149114c7f10ab1bbc7bcc98/README.md#synchronous-and-asynchronous-injection) say
> The MetaMask extension provider is synchronously injected, while the MetaMask mobile provider is asynchronously injected.

But https://github.com/MetaMask/detect-provider/issues/38#issuecomment-1215739459 gave different answer.
> Mobile is different because we don't provide MetaMask through a browser extension, we offer a separate app. Apps can't talk directly to each other, so if you have a dapp open in iOS Chrome, iOS Safari, Android Chrome, Android Firefox, etc., the site can't know that you have MetaMask installed, because no such script is injected on the page like it is in the browser on desktop.

I thought that the latter was probably correct and that the README (and [MetaMask Docs](https://docs.metamask.io/guide/mobile-best-practices.html#the-provider-window-ethereum)) should be amended.

**Comment by mcmire** [comment]
Would it make more sense if we changed the wording to something like this?

> The MetaMask extension provider is synchronously injected, while the MetaMask mobile provider (only available when accessing a dapp inside of the mobile app) is asynchronously injected.

**Comment by uji** [comment]
It looks good. 👍 

[nit]
I think you may want to write that deeplink is recommended as a countermeasure in case the presence of `window.ethereum` cannot be detected.

**Comment by mcmire** [comment]
@uji We could certainly remind people about deeplinking as a way of bypassing the need to detect the provider. That would assume your dapp is so simple that you don't need to connect to the user's wallet at all -- you just want to spawn an action in MetaMask, such as a payment request. Is that use case what you had in mind?

**Comment by uji** [comment]
@mcmire I was thinking of use cases that connect to the user's wallet.
In this case, I thought I needed to transition to the browser inside of the mobile app using deeplink.
Is this a correct understanding?

**Comment by uji** [comment]
@mcmire 
I want to use MetaMask Ethereum provider in a Dapp running in browsers outside of the MetaMask mobile app(such as Google chrome).
`windows.ethereum` isn't injected those browsers, so I thought I needed to use deeplink to transition to the MetaMask mobile app browser.
