### ISSUE TITLE
Reject instead of resolve(null) when `mustBeMetamask` is true

### ISSUE THREAD

**Issue by GabrielBuragev** [MetaMask/detect-provider#73]
Firstly, thanks for your work on this project! 🙂

# Rationale
There are times when multiple wallet provider extensions are installed inside the users browser alongside MetaMask.
Some extensions play together nicely (for example Metamask & Coinbase) but some are simply overwriting the `window.ethereum` property with their own injection (for example Metamask & Frame Companion).

In these cases, i would like to be able to call `await detectEthereumProvider({mustBeMetamask: true})` and get a rejection if no MetaMask was found at `window.ethereum` instead of a null resolution. This way we can handle this error in our dapps and provide some meaningful information to our users as to why they cannot connect.

---
Here is the diff that solved my problem:

```diff
diff --git a/src/index.ts b/src/index.ts
index 2141c3e..f3248ad 100644
--- a/src/index.ts
+++ b/src/index.ts
@@ -40,7 +40,7 @@ function detectEthereumProvider<T = MetaMaskEthereumProvider>({
 
   let handled = false;
 
-  return new Promise((resolve) => {
+  return new Promise((resolve, reject) => {
     if ((window as Window).ethereum) {
 
       handleEthereum();
@@ -72,13 +72,17 @@ function detectEthereumProvider<T = MetaMaskEthereumProvider>({
       if (ethereum && (!mustBeMetaMask || ethereum.isMetaMask)) {
         resolve(ethereum as unknown as T);
       } else {
+        const expectedInjectionMissmatch = mustBeMetaMask && ethereum;
 
-        const message = mustBeMetaMask && ethereum
+        const message = expectedInjectionMissmatch
           ? 'Non-MetaMask window.ethereum detected.'
           : 'Unable to detect window.ethereum.';
 
         !silent && console.error('@metamask/detect-provider:', message);
-        resolve(null);
+
+        if(expectedInjectionMissmatch){
+          reject(new Error(message))
+        }
       }
     }
   });
END
```

**Comment by mcmire** [comment]
We decided that the existing behavior is sufficient.
